apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-combined-demo.yaml

patches:
- target:
    kind: Application
  patch: |-
    kind: Application
    metadata:
      name: .*
    spec:
      destination:
        namespace: demo
      source:
        repoURL: https://github.com/adityaprakash-work/ArgoStack.git