apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-minio
spec:
  template:
    spec:
      containers:
        - name: minio
          resources:
            requests:
              memory: 1Gi