apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-filestash
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-filestash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-filestash
    spec:
      containers:
        - image: 'machines/filestash:b26eb6b'
          imagePullPolicy: Always
          name: filestash
          ports:
            - containerPort: 8334
          volumeMounts:
            - mountPath: /app/data/state/config
              name: config-volume
      volumes:
        - configMap:
            items:
              - key: demo-filestash-config.json
                path: config.json
            name: demo-filestash-cm
          name: config-volume
  strategy:
    blueGreen: 
      activeService: demo-filestash
      previewService: demo-filestash-preview
      autoPromotionEnabled: false