apiVersion: v1
kind: Service
metadata:
  name: demo-filestash
spec:
  ports:
    - name: tcp-demo-filestash
      port: 9001
      targetPort: 8334
  selector:
    app.kubernetes.io/name: demo-filestash
  type: LoadBalancer