kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: demo
  name: workflow-creator
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workflow-creator-binding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: demo
roleRef:
  kind: Role
  name: workflow-creator
  apiGroup: rbac.authorization.k8s.io






